const assert = require('node:assert/strict');
const fs = require('node:fs/promises');

module.exports = async (page, peer, stored, owner) => {
  await page.locator('#rename-collection').click();
  await page.locator('#rename-name').fill('Focus and learning');
  await page.locator('#confirm-collection-edit').click();
  await page.locator('#collection-dialog').waitFor({state: 'hidden'});
  await peer.locator('.collection-folder').filter({hasText: 'Focus and learning'}).waitFor();
  assert.equal(await page.locator('#active-collection-name').textContent(), 'Focus and learning');
  assert.equal(await page.locator('#collection-count').textContent(), '2');

  await page.getByRole('button', {name: 'Remove from collection', exact: true}).first().click();
  await page.waitForFunction(() => document.querySelectorAll('#saved-grid .catalog-card').length === 1);
  await page.getByRole('button', {name: 'Undo', exact: true}).click();
  await page.waitForFunction(() => document.querySelectorAll('#saved-grid .catalog-card').length === 2);
  await page.locator('#delete-collection').click();
  await page.getByRole('button', {name: 'Cancel', exact: true}).click();
  assert.equal(await page.locator('#collection-count').textContent(), '2');
  await page.locator('#delete-collection').click();
  await page.locator('#confirm-collection-edit').click();
  await page.locator('#collection-dialog').waitFor({state: 'hidden'});
  await peer.waitForFunction(() => document.querySelector('#collection-count').textContent === '1');
  await page.getByRole('button', {name: 'Undo', exact: true}).click();
  await page.waitForFunction(() => document.querySelector('#collection-count').textContent === '2');
  await peer.waitForFunction(() => document.querySelector('#collection-count').textContent === '2');
  assert.equal(await page.locator('#saved-grid .catalog-card').count(), 2);

  const before = structuredClone(stored[owner].items);
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#export-collections').click()]);
  const backup = JSON.parse(await fs.readFile(await download.path(), 'utf8'));
  assert.equal(backup.format, 'figuring-out-collections');
  assert.deepEqual(backup.collections, before);
  assert.equal('csrf' in backup, false);
  const upload = value => page.locator('#import-file').setInputFiles({name: 'collections.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(value))});
  const revision = stored[owner].revision;
  await upload({format: 'figuring-out-collections', version: 1, collections: [{id: 'bad', name: 'Bad', items: [{id: 'bad/video/id', title: 'Invalid', kind: 'episode'}]}]});
  await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('invalid saved item'));
  assert.equal(stored[owner].revision, revision, 'Invalid imports do not change saved data');
  await upload(backup);
  await page.locator('#confirm-import').click();
  await page.locator('#import-dialog').waitFor({state: 'hidden'});
  assert.deepEqual(stored[owner].items, before, 'Reimporting a backup does not duplicate existing items');
  await page.locator('#delete-collection').click();
  await page.locator('#confirm-collection-edit').click();
  await page.locator('#collection-dialog').waitFor({state: 'hidden'});
  await upload(backup);
  await page.locator('#confirm-import').click();
  await page.locator('#import-dialog').waitFor({state: 'hidden'});
  assert.deepEqual(stored[owner].items, before, 'A backup restores deleted collections');
  await page.locator('#history-tab').focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#collections-panel').isVisible(), false);
  assert.equal(await page.locator('#history-panel').isVisible(), true);
  await page.reload();
  await page.locator('#history-panel').waitFor();
  assert.equal(await page.locator('#history-tab').getAttribute('aria-selected'), 'true');
  await page.locator('#history-tab').focus();
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('#collections-panel').isVisible(), true);
  assert.equal(await page.locator('#collections-tab').evaluate(el => el === document.activeElement), true);
};
